from __future__ import annotations


class Broker:
    def connect(self): ...
    def get_account(self): ...
    def get_positions(self): ...
    def submit_order(self, order): ...
    def cancel_order(self, order_id): ...
    def modify_order(self, order_id, params): ...
    def get_open_orders(self): ...
    def close_position(self, symbol): ...